# Generated by Django 2.2.12 on 2020-05-20 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_post_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_file',
            field=models.FileField(blank=True, null=True, upload_to='postimages/'),
        ),
        migrations.AddField(
            model_name='post',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
