# Generated by Django 2.2.8 on 2020-04-01 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeimage',
            name='active',
            field=models.BooleanField(null=True),
        ),
    ]
